<div class="hr_3">&#160;</div>
<div class="home_item">
	<div class="title"><?php echo T('联系我们')?></div>
	<div class="content">
		<div class="hr_2">&#160;</div>
		<!--
		<span class="contact_name"><?php echo T('南开大学设备处')?></span><p>
		<span class="contact_address"><?php echo T('天津市南开区卫津路97号')?></span><p>
		<span class="contact_phone"><?php echo T('022-23508813')?></span><p>
		<span class="contact_postcode"><?php echo T('300300')?></span><p>-->
		<h4 class="center"><span class="nav"><?php echo 'Coming Soon'?></span><h4>
		<div class="hr_2">&#160;</div>
		<div class="hr_2">&#160;</div>

	</div>
</div>