<div class="hr_3">&#160;</div>
<div class="form clearfix">
<h3 class="section_title"><?php echo T('重置您的登录密码')?></h3>
<div class="hr_1">&#160;</div>
<div class="form padding_1 clearfix">
<table class="form">
	<tbody>
	<tr>
		<td class="top icon">
			<img src="<?php echo O('user')->icon_url('64')?>" />
		</td>
		<td class="top">
			<form method="post" autocomplete="off">
			<?php echo V('form_error', array('form'=>$form));?>
			<input class="hidden" name="key" value="<?php echo $key?>" />
			<table class="form">
				<tbody>
					<tr>
						<td class="label right nowrap middle"><label><?php echo T('新密码')?></label></td>
						<td class="middle">
							<input type="password" class="text" name="new_pass" value="<?php echo H($form['new_pass'])?>" />
						</td>
					</tr>
					<tr>
						<td class="label right nowrap middle"><label><?php echo T('确认新密码')?></label></td>
						<td class="middle">
							<input type="password" class="text" name="confirm_pass" value="<?php echo H($form['confirm_pass'])?>" />
						</td>
					</tr>
					<tr>
						<td></td>
						<td>
							<input type="submit" name="submit" class="button button_save middle" value="<?php echo T('重置')?>" />
						</td>
					</tr>
				</tbody>
			</table>
			</form>
		</td>
	</tr>
	</tbody>
</table>
</div>
</div>
