<?php 
$root = Product_Category_Model::root('consumable');
$categories = $root->children()->filter(':sort(weight A)');
if ($categories->total_count()) :
$images = Config::get('mall.home_images');
$slider_id = 'slider_'. uniqid();
?>
<?php echo V('prod_consumable:mall/sub_header'); ?>
<div class="hr_3">&#160;</div>
<div class="slider-wrapper">
	<div class="nivoSlider slider" id="<?php echo $slider_id;?>">
		<?php foreach ($images as $image) :?>
			<?php 
				$extra = array();
				$extra['src'] = 'src="' . _C($image['path']) .'" ';
				if ($image['title']) $extra['title'] = 'title="' . $image['title'] . '" ';
				
				$img_body = '<img ' . join(' ', $extra) . ' />';
				
				echo isset($image['link']) ? URI::anchor($image['link'], $img_body, ' target="_blank"') : $img_body;
			?>
		<?php endforeach;?>
	</div>
</div>
<script type="text/javascript">
(function($) {
    $('#<?php echo $slider_id;?>').nivoSlider({
    	effect: 'random',
    	animSpeed: 1000,
    	pauseTime: 5000,
    	controlNav: true,
    	captionOpacity: 0.4
    });
    
})(jQuery);
</script>
<div class="hr_2">&#160;</div>
<div class="home_item category_view">
	<div class="title"><?php echo HT('按分类查看'); ?></div>
	<ul class="category_list clearfix">
		<?php
			$root = Product_Category_Model::root('consumable');
			$categories = $root->children()->filter(':sort(weight A)');
			foreach ($categories as $category) {
				echo V('prod_consumable:mall/home/category_item', array('category'=>$category));
			}
		?>
	</ul>
</div>
<div class="hr_2">&#160;</div>
<div class="vendor_view">
	<?php
		$per_page = 5;
		$vendors = Q("vendor_scope[name=product_type.consumable][expire_date>0] vendor[approve_date>0]")->limit($per_page);
	?>
	<div class="title">
		<div class="float_right"><?php echo URI::anchor(URI::url('!mall/home/index.vendor'), T('更多 &#187;'), 'class="blue"'); ?></div>
		<?php echo HT('按供应商查看'); ?>
	</div>
	<table class="vendor_list flexible">
		<tbody>
			<tr>
				<th class="nav"></th>
				<th class="separator"></th>
				<th class="nowrap left nav"><?php echo T('供应商名称')?></th>
				<th class="separator"></th>
				<th class="nowrap nav center"><?php echo T('评价')?></th>
			</tr>
			<?php
				$num = 1;
				foreach ($vendors as $vendor) {
					if ($num % 2) $class = "color_row";
					else $class = "";
					$num ++;
					echo V('prod_consumable:mall/home/vendor_item', array('vendor'=>$vendor, 'class' => $class));
				}
			?>
		<tbody>
	</table>
</div>
<?php endif;?>
