<?php
	$me = L('ME');
	$no_error = ($form->no_error !== FALSE);
	$require = (string) V('form_require');
?>
<div class="hr_1">&#160;</div>
<form method="post" autocomplete="off" action="<?php echo URI::url() ?>">
<div class="form padding_2">
	<?php echo V('form_error', array('form'=>$form));?>
	<h4><?php echo HT('常规信息'); ?></h4>
	<div class="hr_1">&#160;</div>
	<table class="form">
		<tbody>
			<tr>
				<td class="label right nowrap middle"><?php echo T('类别')?></td>
				<td class="middle nowrap" colspan="4">
				<?php
					$types = Product_Model::get_types();
					$available_types = $types; // TODO 筛选当前 vendor 可添加的 type(xiaopei.li@2012-03-08)
					echo $types[$product->type];

					echo '&#160;';

					$category = O('product_category', $form['category']);
					$root = Product_Category_Model::root($product->type);

					echo Widget::factory('application:category_selector', array(
						'category'=> $category,
						'root'=>$root,
						'name'=>'category',
						'ajax'=>TRUE,
					));
				?>
				</td>
			</tr>
			<tr>
				<td class="label right nowrap middle"><?php echo T('名称')?></td>
				<td class="middle nowrap" colspan="4">
					<input name="name" class="text" size="60" value="<?php echo H($product->name); ?>" <?php echo !in_array('name', $merge_keys) ? : 'disabled' ?> /><?php echo $require?>
				</td>
			</tr>
			<tr>
				<td class="label right nowrap middle"><?php echo T('生产商')?></td>
				<td class="middle tight nowrap">
					<input name="manufacturer" class="text" size="20" value="<?php echo H($form['manufacturer']); ?>" <?php echo !in_array('manufacturer', $merge_keys) ? : 'disabled' ?> /><?php echo $require?>
				</td>
				<td class="label right nowrap middle"><?php echo T('目录号')?></td>
				<td class="middle">
					<input name="catalog_no" class="text" size="20" value="<?php echo H($form['catalog_no']); ?>" <?php echo !in_array('catalog_no', $merge_keys) ? : 'disabled' ?> /><?php echo $require?>
				</td>
			</tr>
			<tr>
				<td class="label right nowrap middle"><?php echo T('品牌')?></td>
				<td class="middle">
					<input name="brand" class="text" size="20" value="<?php echo H($form['brand']); ?>" <?php echo !in_array('brand', $merge_keys) ? : 'disabled' ?> />
				</td>
				<td class="label right nowrap middle"><?php echo T('型号')?></td>
				<td class="middle">
					<input name="model" class="text" size="20" value="<?php echo H($form['model']); ?>" <?php echo !in_array('model', $merge_keys) ? : 'disabled' ?> />
				</td>
			</tr>
			<tr>
				<td class="label right nowrap middle"><?php echo T('包装')?></td>
				<td class="middle">
					<input name="package" class="text" size="20" value="<?php echo H($form['package']); ?>" <?php echo !in_array('package', $merge_keys) ? : 'disabled' ?> /><?php echo $require?>
				</td>
				<td class="label right nowrap middle"><?php echo T('规格')?></td>
				<td class="middle">
					<input name="spec" class="text" size="20" value="<?php echo H($form['spec']); ?>" <?php echo !in_array('spec', $merge_keys) ? : 'disabled' ?> /><?php echo $require?>
				</td>
			</tr>
			<tr>
				<td class="label right middle nowrap"><?php echo HT('关键字'); ?></td>
				<td class="middle nowrap" colspan="4">
					<?php
						$root = Tag_Model::root('product_keyword');
						echo Widget::factory('application:multi_tag_selector',
										array(
											// TODO 'autocomplete'=> URI::url("autocomplete/tags.$root->id"),
											'name'=>'keywords',
											'value'=> $form['keywords'],
											'size'=>'60',
											'allow_creating'=>TRUE,
											'token_tip' => T('输入每个关键字后请按回车键')
											));
					?>
				</td>
			</tr>
			<tr>
				<td class="label right nowrap top"><?php echo T('说明')?></td>
				<td class="middle" colspan="4">
					<textarea name="description" class="text autogrow" cols="60" rows="5"><?php echo H($form['description']); ?></textarea>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<?php
$sections = new ArrayIterator;
$ret =  Event::trigger('form[admin.product].approve.sections', NULL, $form, $sections);
echo implode('', (array)$sections);
?>
<div class="form padding_2">
	<h4><?php echo HT('其他'); ?></h4>
	<div class="hr_1">&#160;</div>
	<table class="form">
		<tbody>
		<tr>
			<td class="label right nowrap"><?php echo HT('过期日期') ?></td>
			<td class="left">
				<?php
					if (!isset($form['has_expire_date']) && !$product->expire_date) {
						// 激活时默认不设过期
						$has_expire_date = 0;
					}
					else {
						$has_expire_date = $form->no_error ? ($product->expire_date > 0) : $form['has_expire_date'];
					}
					echo Form::checkbox('has_expire_date', $has_expire_date, NULL, 'class="middle monitor"'); ?>
				<input name="expire_date" class="text toggle_status:has_expire_date enable_on:on date" size="40" value="<?php echo H($no_error ? $product->expire_date : $form['expire_date'])?>" q-date_format="<?php echo HT('$year年$month月$day日 $hour时$min分$sec秒')?>"/></td>
		</tr>
		<tr>
			<td class="label right nowrap top"><?php echo T('备注')?></td>
			<td class="left" colspan="3">
				<textarea name="note" class="text autogrow" cols="60" rows="5"><?php echo H($no_error ? $product->note : $form['note'])?></textarea>
			</td>
		</tr>
		</tbody>
	</table>
</div>
<div class="form padding_2">
		<input type="submit" name="submit" class="button button_save" value="<?php echo HT('确认审核通过')?>" />
</div>
</form>
