<div class="hr_1">&#160;</div>
<div class="form padding_1 clearfix">
<?php
	$no_error = $form->no_error;
?>
	<form method="post"
	autocomplete="off"
	q-object="soldout"
	q-event="submit"
	q-static="<?php echo H(array('id'=>$product->id))?>">
		<table class="form flexible">
			<tr>
				<td class="label right nowrap top"><?php echo HT('理由')?></td>
				<td class="left">
				  <textarea name="soldout_reason" class="text" rows="5" cols="40"></textarea>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" name="submit" class="button button_delete" value="<?php echo HT('下架')?>" />
				</td>
			</tr>
		</table>
	</form>
</div>
