<div class="hr_1">&#160;</div>
<?php
echo $pagination;

$table = Widget::factory('table');
$table->name = 'snapshots'; // 可根据 $table->name 绑定事件

$columns = array(
	'name'=>array(
		'title'=>T('商品名称'),
		'align'=>'left',
		'nowrap'=>TRUE
    ),
	'mtime' => array(
    	'title'=>T('版本生成时间'),
    	'align'=>'left',
    	'nowrap'=>TRUE
		),
    'unit_price' => array(
    	'title'=>T('价格'),
    	'align'=>'left',
    	'nowrap'=>TRUE
    ),
    'vendor_note'=>array(
        'title'=>T('备注'),
        'align'=>'left',
    ));

$table->add_columns($columns);

$table->empty_message = HT('此商品无历史快照');

foreach ($snapshots as $snapshot) {
	$table->add_row( array(
		'name' => V('admin:vendor_product/snapshot/name', array('snapshot'=>$snapshot)),
		'mtime' => $snapshot->mtime ? : '--',
		'unit_price' => V('application:common/price', array('price'=>$snapshot->unit_price)),
		'vendor_note' => H($snapshot->vendor_note, TRUE),
	));

}

echo $table;
