<div class="form padding_1">
<form class="view object:category_edit event:submit static:<?php echo H(array('id'=>$category->id, 'parent'=>$parent, 'uniqid'=>$uniqid, 'parent_uniqid'=>$parent_uniqid, 'is_root'=>$is_root, 'collapsed'=>$collapsed)) ?>">
	<table class="form">
		<tbody>
			<tr>
				<td class="right nowrap middle"><?php echo T('类别')?></td>
				<td class="middle">
					<input type="text" class="text" name="name"  size="30" value="<?php echo H($category->name) ?>" />
				</td>
			</tr>
			<tr>
				<td class="right nowrap top"><?php echo T('简介')?></td>
				<td class="middle">
					<textarea class="text autogrow" name="description" cols="30" rows="5"><?php echo H($category->description)?></textarea>
				</td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" name="submit" class="button button_save middle" value="<?php echo T('提交')?>" /> </td>
			</tr>
		</tbody>
	</table>
</form>
</div>
