<span class="price"><?php
	$price = 0; 
	$order_items = Q("order_item[order={$order}][price>0]");
	foreach ($order_items as $order_item) {
		$price += $order_item->price;
	}
	echo Number::currency($price); 
?></span>
<?php
$has_inquiry = !!Q("order_item[order={$order}][price<0]")->total_count();
if ($has_inquiry):
	if ($long):
		?>
		<span class="price_inquiry"><?php echo HT('(待询价商品未计入)'); ?></span>
		<?php
	else:
?>	
	<span class="price_inquiry"><?php echo HT('(待询价)'); ?></span>
<?php
	endif;
endif;