<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<title>
	<?php echo $title ? T(Config::get('page.title_pattern'), array('%title'=>$title)) : Config::get('page.title_default');
 ?>
</title>
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<?php /*<meta name="viewport" content="user-scalable=yes, width=device-width, minimum-scale=1.0, maximum-scale=1.0" /> */ ?>
<base href="<?php echo Config::get('system.base_url') ?>" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="<?php echo _C('images/icon_touch.png') ?>" />
<?php echo $this->controller->load_css(); ?>
<body>
<div class="panel right padding_1">
<a href="#" onclick="javascript:window.close(); return false" class="button button_delete"><?php echo T('关闭'); ?></a>
</div>
<div class="padding_2 clearfix">
<h1><?php echo I18N::T('labs', '注册须知'); ?></h1>
<div class="hr_1"><hr/></div>
<?php echo H(Site::get('people.signup.doc'), TRUE);?>
</div>
</body>
</html>
