<div class="form padding_1">
<form method="post">
<?php echo V('form_error', array('form'=>$form));?>
<?php $require = (string) V('form_require'); ?>
<table class="form flexible">
	<tbody>
	<tr>
		<td class="label left nowrap">
	 		<?php echo T('标题'); ?>
		</td>
		<td class="top">
			<input name="title" class="text" size="60" value="<?php echo H($form['title'])?>" />
		</td>
	</tr>
	<tr>
		<td class="label left top nowrap"><?php echo T('内容')?></td>
		<td class="top">
		<textarea name="content" rows="9" cols="60" class="rich-textarea text autogrow"><?php echo H($form['content']) ?></textarea>
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
			<input type="submit" name="submit" class="button button_add" value="<?php echo T('添加')?>" />
		</td>
	</tr>
</table>
</form>
</div>
