<div class="hr_1">&#160;</div>
<div class="product_detail clearfix">
	<table class="form flexible">
		<tbody>
			<tr>
				<td class="top icon">
					<?php echo $product->icon('128'); ?>
				</td>
				<td class="top flexible">
					<div class="hgroup">
						<h2>
						<?php echo URI::anchor($product->url(), H($product->name)) ?>
						</h2>
						<h3>
							<?php
							echo HT('%manufacture %catalog_no', array(
								'%manufacture' => $product->manufacturer,
								'%catalog_no' => $product->catalog_no
							));
							?>
						</h3>
						<div>
						<span class="type">
						<?php
							$types = [
								'chem_reagent' => '化学试剂',
								'bio_reagent' => '生物试剂',
								'consumable' => '耗材'
							];
							echo $types[$product->type];
						?>
						</span>
						<?php
						echo V('application:tag/path', array('tag' => $product->category));
						?>
						</div>
					</div>
					<div class="hr_2"></div>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="hr_2"></div>
	<?php echo $secondary_tabs ?>
	<?php echo $secondary_tabs->content ?>
</div>
