<div class="logo">
	<a href="<?php echo URI::url('/')?>"><img src="<?php echo _C('images/logo.png') ?>" /></a>
</div>
<div class="menu">
	<a class="middle" href="<?php echo URI::url('!people/cart');?>">
		<?php echo HT('购物车')?>
	</a>
	<span class="middle">(10)</span>
	<span class="separator middle">|</span>
	<a class="middle" href="<?php echo URI::url('logout')?>"><?php echo HT('登出') ?></a>
</div>

