<?php
	if (Input::route() != $_SESSION['system.current_layout_url']) {
		$_SESSION['system.last_layout_url'] = $_SESSION['system.current_layout_url'];
	}
	$_SESSION['system.current_layout_url'] = Input::route();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<title>
	<?php echo H($title ? T(Config::get('page.title_pattern'), array('%title'=>$title)) : Config::get('page.title_default'));
 ?>
</title>
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<base href="<?php echo Config::get('system.base_url') ?>" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="<?php echo _C('images/icon_touch.png') ?>" />
<?php echo $this->controller->load_css(); ?>
<?php echo $this->controller->load_js(TRUE); ?>
<script>
(function($){
	Q['24hour'] = <?php echo JS::quote(!!Config::get('system.24hour')); ?>;
})(jQuery);
</script>
</head>
<body>
<div id="wrapper">
	<div id="header"><div class="header_content">
		<?php echo $this->header; ?>
	</div></div>
	<?php if( isset( $this->sub_header ) ) { ?>
		<div id="sub_header" class="clearfix">
			<?php echo $this->sub_header; ?>
		</div>
	<?php } ?>
	<div id="body" class="clearfix">
		<div id="col1_center_container">
			<?php echo V('message'); ?>
			<?php echo $this->body; ?>
		</div>
	</div>
	<div id="footer"><div class="footer_content">
		<?php echo $this->footer; ?>
	</div></div>
</div>
	<?php echo $this->controller->load_js(FALSE); ?>
</body>
</html>

