<?php 
	$auth_backends = Config::get('auth.backends');
	$is_hide = FALSE;
	if (count($auth_backends) > 1) {
		$hidden = array();
		foreach ($auth_backends as $key => $backend) {
			if ($backend['readonly']) {
				$hidden[] = $key;
			}
		}
		if (count($hidden)) $class = "toggle:".$this->name.' hide_on:'.join(' hide_on:', $hidden);
	}
	else {
		$default_backend = $this->default_backend ?: Config::get('auth.default_backend');
		if ($auth_backends[$default_backend]['readonly']) {
			$is_hide = TRUE;
		}
	}
	
	if (!$me->access('管理所有内容')) {
		$class = NULL;
		list($token, $backend) = Auth::parse_token($user->token);
		if ($auth_backends[$backend]['readonly']) {
			$is_hide = TRUE;
		}
	}
	if (!$is_hide):
?>
<?php if($me->id == $user->id): ?>
<tr class="<?php echo $class?>">
	<td class="label right nowrap middle"><?php echo T('旧密码')?></td>
	<td class="middle"><input name="old_pass" type="password" class="text" tabindex="2" /></td>
</tr>
<?php endif; ?>
<tr class="<?php echo $class?>">
	<td class="label right nowrap middle"><?php echo T('新密码')?></td>
	<td class="middle">
		<input type="password" style="display:none" />
		<input type="password" name="new_pass" class="text" tabindex="3" />
		<?php if ($me->id != $user->id): ?>
		<?php echo Form::checkbox('must_change_password', Input::form('must_change_password'), T('下一次登录时修改密码'), 'tabindex="5" class="middle"', 'class="middle"'); ?>
		<?php endif; ?>
	</td>
</tr>
<tr class="<?php echo $class?>">
	<td class="label right nowrap middle"><?php echo T('确认新密码')?></td>
	<td class="middle">
		<input type="password" name="confirm_pass" class="text" tabindex="4" />
	</td>
</tr>
<?php endif; ?>
