<div class="hr_1">&#160;</div>
<?php echo $secondary_tabs;?>
<div class="hr_1">&#160;</div>
<?php
// 10362 【Win 8，firfox】【南通大学】0.1.0，mall-old，买方管理，添加买方功能去掉
/*
<div class="panel padding_1">
	<a class="button button_add" href="<?php echo URI::url('!admin/user/add')?>"><?php echo T('添加新用户')?></a>
</div>
 */?>
<?php
echo $pagination;

$table = Widget::factory('table');
$table->name = 'admin_users';
$table->form = $form;
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;


$table->add_columns(array(
    '@'=>array(
        'nowrap'=>TRUE
    ),
    'name'=>array(
        'title'=>T('姓名'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'name', 'value' => $form['name'])),
        	'value' => $form['name'] ? H($form['name']) : NULL
        ),
        'nowrap'=>TRUE,
        'align'=>'left'
    ),
    'contact_info'=>array(
        'title'=>T('联系方式'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'contact', 'value' => $form['contact'])),
        	'value' => H($form['contact'] ?: NULL),
        	'field' => 'contact'
        ),
        'nowrap'=>TRUE,
        'align'=>'left'
    ),
    'address'=>array(
        'title'=>T('地址'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'address', 'value' => $form['address'])),
        	'value' => $form['address'] ? H($form['address']) : NULL
        ),
        'nowrap'=>TRUE,
        'extra_class'=>'flexible'
    ),
    'rest'=>array(
        'align'=>'right',
        'nowrap'=>TRUE
    )
));

$table->empty_message = T('没有符合条件的用户!');

foreach($users as $user)  {

    $links = $user->links('admin_index');

    $table->add_row(array(
        '@'=>array(
            'view'=>$user->icon('32', 'style="display:block"'),
            'extra'=>'style="padding:4px" align="right"'
        ),
        'name'=> array(
        	'view' => V('admin:user_table/data/name', array('user'=>$user)),
        	'light' => TRUE
        ),
        'contact_info'=>V('admin:user_table/data/contact_info', array('user'=>$user)),
        'address'=> array(
        	'view' => V('admin:user_table/data/address', array('user'=>$user)),
        	'light' => TRUE
        ),
        'rest'=>Widget::factory('application:links', array('links'=>$links))
    ));
}

echo $table;
?>
