<?php $customer = $statement->customer; ?>
<div class="padding_3" style="width:300px;">
	<p class="description"><?php echo T('支付完成前，请不要关闭此支付验证窗口') ?></p>
	<p class="description"><?php echo T('支付完成后，请根据您网上财务支付的情况点击以下按钮') ?></p>
	<p class="description"><?php echo T('如支付遇到问题，请联系管理员') ?></p>
	<div class="hr_3">&#160;</div>
	<a class="button button_tick" q-object="complete_pay" q-event="click" q-static="<?php echo H(array('sid'=>$statement->id))?>"><?php echo T('完成付款')?></a>
	<a class="button button_cancel" q-object="fail_pay" q-event="click" q-static="<?php echo H(array('sid'=>$statement->id))?>"><?php echo T('付款遇到问题')?></a>
</div>
