<?php if ($total > $per_page) : 

$current_page = floor($start / $per_page) + 1;
$total_pages = ceil($total / $per_page);
$max_pages = 5;

$url = $this->url ?: URI::url('');
$st = $this->query_key ?: 'st';

if ($total_pages > 1) :

$lamda_func = 'pagination_'.uniqid();

?>
<div class="pagination">
<?php 
	$f=$current_page - floor($max_pages/2);
	$t=$current_page + floor($max_pages/2);
	if ($f<1) {
		$f=1;
		$t=$f+$max_pages-1;
	}
	if ($t>$total_pages) {
		$t=$total_pages;
		$f=$t-$max_pages+1;
		if($f<1)$f=1;
	}

	if ($current_page != 1) {
		echo '<a href="'.URI::url($url, array($st=>'0')).'">&#171;'.HT('首页').'</a>';
	}

	if ($current_page > 1) {
		echo '<a href="'.URI::url($url, array($st=>($current_page - 2)*$per_page)).'">'.HT('上一页').'</a>';
	}

	//	echo '<span class="current">'.HT('第%num页', array('%num'=>$i)).'</span>';

	for ($i=$f;$i<=$t;$i++) {
		if ($i == $current_page) {
			echo '<span class="current">'.$i.'</span>';
		}
		else {
			echo '<a href="'.URI::url($url, array($st=>($i - 1)*$per_page)).'">'.$i.'</a>';
		}
	}

	if ($current_page < $total_pages) {
		echo '<a href="'.URI::url($url, array($st=>($current_page)*$per_page)).'">'.HT('下一页').'</a>';
	}

	if ($current_page != $total_pages ) {
		echo '<a href="'.URI::url($url, array($st => ($total_pages - 1) * $per_page)) .'">'.HT('尾页').'&#187;</a>'; 
	}
	else {
		if ($total < $total_found) {
			echo '<br/>';
			echo HT('结果过多, 未全部显示, 请缩小搜索范围再试');
		}
	}
?>
</div>
<?php 	endif;
endif; 


