<?php
// $comments = Q("$product order_item order_item_comment:limit(5)");
$comments = Q("product[id=$product->id] order_item order_item_comment");

$table = Widget::factory('table');
$table->name = 'product_comment_list';

$table->add_columns(
	array(
		'author' => array(
			'title' => HT('发布者'),
			),
		'ratings' => array(
			'title' => HT('评价'),
			),
		'content' => array(
			'title' => HT('评论内容'),
			),
		)
	);

foreach ($comments as $comment) {
	$table->add_row( array(
		'author' => V('application:widgets/order_item_comment/author', array('comment'=>$comment)),
		'ratings' => Widget::factory('comment_ratings', array(
						   'comment' => $comment,
						   )),
		'content' => V('application:widgets/order_item_comment/content', array('comment'=>$comment)),
	));
}

echo $table;
