<?php
// echo JS::load_async('application:widgets/jquery.rateit');
// echo CSS::load_async('application:widgets/rateit');

$default_min_value = 0;
$default_max_value = 5;

$min_value = $default_min_value;
$max_value = $default_max_value;

$div = '<div class="rateit" data-rateit-value="%value" data-rateit-min="%min_value" data-rateit-max="%max_value" data-rateit-ispreset="true" data-rateit-readonly="true"></div>';

echo strtr($div, array(
	'%value' => $value,
	'%min_value' => $min_value,
	'%max_value' => $max_value,
));
