<?php
$root_id = $root->root->id ? $root->root->id : $root->id;
if ($tag->root->id != $root_id) {
	$tag = $root;
}

$uniqid = 'tag_selector_'.uniqid();
$name = $this->name ?: 'tag_id';

echo JS::load_async('application:widgets/tag_selector');
$opt = array(
	'uniqid' => $uniqid,
	'root_id' => $root->id,
	'url' => $ajax_url ?: URI::url('tags'),
	'name' => $name,
	'ajax' => $ajax
);
?>
<div class="tag_selector text_like <?php echo $this->class?> <?php echo $uniqid?>">
<?php echo V('widgets/tag_selector/container',array(
			'tag'=>$tag,
			'root'=>$root,
			'root_name' =>$root_name,
			'name'=>$name,
			'uniqid' => $uniqid,
	));
?>
</div>
<script>
Q.js_ready('application:widgets/tag_selector', function(){
	var opt = <?php echo JS::quote($opt) ?>;
	jQuery('.' + opt.uniqid).tagSelector(opt);
});
</script>
