<?php
$uniqid = 'user_'.uniqid();

$user = is_object($this->user) ? $this->user : O('user', $this->user);
$autocomplete = $this->autocomplete ?: URI::url('autocomplete/user');


$size = $this->size ?: 40;

if ($user->id) {
	$name = $user->name;
}
else {
	$name = '';
}

?>
<input id="<?php echo $uniqid?>_user" name="<?php echo $this->name ?>" type="hidden" value="<?php echo $user->id?>" />
<input id="<?php echo $uniqid?>_user_name" <?php echo $cardread_str;?> class="text middle select_on_focus autocomplete:<?php echo H($autocomplete) ?> autocomplete_alt:#<?php echo $uniqid?>_user" size="<?php echo $size?>"
 value="<?php echo H($name) ?>" q-tooltip="<?php echo T('请输入关键字并选择') ;?>" />