#!/bin/bash
# 备份逻辑
# - 每小时备份 1 次, 备份内容包括客户的 site 目录(但不包括升级脚本运行前备份数据库的目录 private/backup)及数据库
# - 每天0点删除前第二天0点外的每小时备份
# - 每周日删除8周前除周日的每天备份
# - 每次系统升级前应使用 -a 选项备份所有内容
# (xiaopei.li@2012-02-17)

# uncomment below to test
# set -x

# BAKLIST 是需要备份的 site 列表, 格式为 "site_id"
BAKLIST=/etc/mall/proj_list

# 存放备份的目录
BAKBASE=/backups

# 备份日志
LOGFILE=$BAKBASE/backup.log
touch $LOGFILE

DBUSER=genee
DBPREFIX=mall_

TIMESTAMP=`date "+%Y/%m/%d %H:%M"`
FILENAME_TIMESTAMP=`date "+%Y%m%d_%H%M" -d "$TIMESTAMP"`

while read SITE_ID; do
	DBNAME=$DBPREFIX$SITE_ID
	echo "$TIMESTAMP 生成 $DBNAME 数据库备份..." >> $LOGFILE
	SITE_BAKBASE=$BAK_BASE/mall/$SITE_ID
	mkdir -p $SITE_BAKBASE
	mysqldump -u $DBUSER $DBNAME | bzip2 > $SITE_BAKBASE/$FILENAME_TIMESTAMP.sql
done < $BAKLIST
