<?php $comment_id = 'comment_delete_'.uniqid(); ?>
<div id="<?php echo $comment_id?>" class="form comment padding_1">
<table width="100%">
<tr>
<td class="icon top"><?php echo $comment->author->icon(32) ?></td>
<td class="content_wrap left top lpadding_1" style="width:100%">
	<?php if (L('ME')->is_allowed_to('删除', $comment)): ?>
	<div class="float_right">
		<a href="#" class="blue remove_button" onclick="return false" q-widget="comments" q-object="delete" q-event="click" q-static="<?php echo H(array('id'=>$comment->id, 'comment_id'=>$comment_id, 'list_id'=>$list_id, 'oname'=>$object->name(), 'oid'=>$object->id)) ?>">&#160;</a>
	</div>
	<?php endif; ?>
    <span><?php
    if ($comment->is_log) {
        echo HT('系统');
    }
    else {
        $comment->author->render();
    }?>: </span>
    <div style="width:450px">
        <?php echo H($comment->content, TRUE) ?>
    </div>
	<span class="time">(<?php echo Date::fuzzy($comment->ctime, TRUE) ?>)</span>
</td>	
</table>
</div>
