<div class="form padding_2">
<table class="form">
	<tbody>
	<tr>
		<td class="top icon">
			<img src="images/icons/signup_big.png" />
		</td>
		<td class="top" style="padding-left:10px">
		<h1><?php echo I18N::T('people', '请重置您的登录密码') ?></h1>
		<div class="hr_1">&#160;</div>
		<form method="post" autocomplete="off" action="<?php echo URI::url();?>">
		<?php echo V('form_error', array('form'=>$form));?>
			<table>
				<tbody>
					<tr>
						<td class="right nowrap middle"><?php echo I18N::T('people', '新密码')?></td>
						<td class="middle"><input type="password" name="new_pass" class="text" size="20" /></td>
					</tr>
					<tr>
						<td class="right nowrap middle"><?php echo I18N::T('people', '确认密码')?></td>
						<td class="middle"><input type="password" name="confirm_pass" class="text" size="20" /></td>
					</tr>
					<tr>
						<td colspan="2" class="hr_1">&#160;</td>
					</tr>
					<tr>
						<td></td>
						<td>
							<input type="submit" name="submit" class="button button_save" value="<?php echo I18N::T('people', '保存')?>" />
						</td>
					</tr>
				</tbody>
			</table>
		</form>
		</td>
	</tr>
	</tbody>
</table>
</div>

