<h2 class="section_title">
		<span class="middle"><?php echo HT('生物试剂') ?></span>
</h2>
<div class="padding_2" style="padding-top:5px">
<table class="form product_info_form" style="min-width:400px">
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo HT('运输条件')?></span></td>
		<td colspan="3"><?php echo H($product->transport_cond) ?></td>
	</tr>
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo HT('保存条件')?></span></td>
		<td colspan="3"><?php echo H($product->storage_cond) ?></td>
	</tr>
</table>
</div>