<div class="hr_1">&#160;</div>
<?php echo $secondary_tabs; ?>
<div class="hr_1">&#160;</div>
<div class="panel padding_1">
	<a class="button button_add" 
	q-object="add_customer_member" 
	q-event="click"  
	q-static="<?php echo H(array('cid'=>$customer->id))?>" 
	href="#">
	<?php echo T('添加成员')?></a>
</div>
<?php
echo $pagination;

$table = Widget::factory('table');
$table->name = 'admin_customer_users';
$table->form = $form;
$table->sort_asc = $sort_asc;
$table->sort_by = $sort_by;

$table->add_columns(array(
    '@'=>array(
        'nowrap'=>TRUE
    ),
    'name'=>array(
        'title'=>T('姓名'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'name', 'value' => $form['name'])),
        	'value' => $form['name'] ? H($form['name']) : NULL
        ),
        'nowrap'=>TRUE,
        'align'=>'left'
    ),
    'contact_info'=>array(
        'title'=>T('联系方式'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'contact', 'value' => $form['contact'])),
        	'value' => H($form['contact'] ?: NULL),
        	'field' => 'contact'
        ),
        'nowrap'=>TRUE,
        'align'=>'left'
    ),
    'address'=>array(
        'title'=>T('地址'),
        'filter' => array(
        	'form' => V('admin:user_table/filters/input', array('name' => 'address', 'value' => $form['address'])),
        	'value' => $form['address'] ? H($form['address']) : NULL
        ),
        'nowrap'=>TRUE,
        'extra_class'=>'flexible'
    ),
    'rest'=>array(
        'align'=>'right',
        'nowrap'=>TRUE
    )
));

$table->empty_message = T('没有符合条件的用户!');

foreach($users as $user)  {

    $links = $user->links('customer_index');

	if ($user->id != $customer->owner->id) {
		$links['delete'] = array(
			'url' => '#',
			'text' => T('移除'),
			'extra' =>'class="blue" '.
			'q-object="delete_customer_user" '.
			'q-event="click" '.
			'q-static="'.H(array('uid'=>$user->id)).'"'
			);
	}

    $table->add_row(array(
        '@'=>array(
            'view'=>$user->icon('32', 'style="display:block"'),
            'extra'=>'style="padding:4px" align="right"'
        ),
        'name'=> array(
        	'view' => V('admin:user_table/data/name', array('user'=>$user)),
        	'light' => TRUE
        ),
        'contact_info'=>V('admin:user_table/data/contact_info', array('user'=>$user)),
        'address'=> array(
        	'view' => V('admin:user_table/data/address', array('user'=>$user)),
        	'light' => TRUE
        ),
        'rest'=>Widget::factory('application:links', array('links'=>$links))
    ));
}

echo $table;