<li class="category_item">
	<div class="icon">
		<?php echo $category->icon(64); ?>
	</div>
	<div class="info">
		<a href="<?php echo $category->url();?>" class="info_title"><?php echo HT($category->name); ?></a>
		<div class="subcategories">
		<?php
			$children = Q("product_category[parent=$category]:sort(weight A)");
			$links = array();
			foreach($children as $c) {
				$links[] = URI::anchor($c->url(), H($c->name), 'class="category_link"');
			}

			echo implode(', ', $links);
			if ($category->description) :
		?>
		
		<p class="description" style="font-size:12px;color:#666666"><?php echo $category->description; ?></p>
		<?php endif; ?>
		</div>
	</div>
</li>

