<?php
$config['product_service']['fields']['name'] = array('type' => 'rt_field');
$config['product_service']['fields']['group_name'] = array('type' => 'rt_attr_string');
$config['product_service']['fields']['spec'] = array('type'=> 'rt_field');
$config['product_service']['fields']['package'] = array('type'=> 'rt_field');
$config['product_service']['fields']['catalog_no'] = array('type' => 'rt_field');
$config['product_service']['fields']['group_search'] = array('type' => 'rt_attr_string');
$config['product_service']['fields']['description'] = array('type' => 'rt_field');
$config['product_service']['fields']['keywords'] = array('type' => 'rt_field');
$config['product_service']['fields']['vendor_name'] = array('type'=> 'rt_field');
$config['product_service']['fields']['category'] = array('type' => 'rt_attr_multi_64');
$config['product_service']['fields']['vendor_id'] = array('type' => 'rt_attr_bigint');
$config['product_service']['fields']['is_frozen'] = array('type'=> 'rt_attr_uint');
$config['product_service']['fields']['is_sale'] = array('type'=> 'rt_attr_uint');
$config['product_service']['fields']['supply_time'] = array('type' => 'rt_attr_uint');
$config['product_service']['fields']['stock_status'] = array('type' => 'rt_attr_uint');
$config['product_service']['fields']['vendor_note'] = array('type'=> 'rt_field');
$config['product_service']['fields']['price'] = array('type'=> 'rt_attr_float');
$config['product_service']['fields']['publish_date'] = array('type'=> 'rt_attr_bigint');
$config['product_service']['fields']['approve_date'] = array('type'=> 'rt_attr_bigint');
$config['product_service']['fields']['ctime'] = array('type' => 'rt_attr_bigint');
$config['product_service']['fields']['vendor_short_name'] = array('type' => 'rt_field');
$config['product_service']['fields']['vendor_short_name_abbr'] = array('type' => 'rt_attr_string');
$config['product_service']['fields']['manufacturer'] = array('type'=> 'rt_field');
$config['product_service']['fields']['manufacturer_abbr'] = array('type' => 'rt_attr_string');
$config['product_service']['fields']['brand'] = array('type' => 'rt_field');
$config['product_service']['fields']['group_brand'] = array('type' => 'rt_attr_string');
$config['product_service']['fields']['price_range'] = array('type'=> 'rt_attr_bigint');
$config['product_service']['fields']['sales'] = array('type'=>'rt_attr_bigint');
$config['product_service']['fields']['weight'] = array('type' => 'rt_attr_bigint');
$config['product_service']['fields']['vendor_weight'] = array('type' => 'rt_attr_bigint');
$config['product_service']['fields']['expire_date'] = array('type'=>'rt_attr_bigint');
$config['product_service']['fields']['valid_fields'] = array('type'=>'rt_attr_bigint');