<div class="form padding_1">
<form class="view object:rename_form event:submit">
	<?php echo Form::hidden('path', $path); ?>
	<?php echo Form::hidden('old_name', $name); ?>
	<?php echo Form::hidden('form_token', $form_token)?>
	<?php echo V('form_error', ['form'=>$form]);?>
	<table class="form">
		<tbody>
			<tr>	
				<td class="right nowrap middle"><?php echo T('名称')?></td>
				<td class="middle">
					<input type="text" class="text" name="name" value="<?php echo H($name ?: 'untitled') ?>" />
				</td>
			</tr>	
			<tr>
				<td></td>
				<td><input type="submit" name="submit" class="button button_save middle" value="<?php echo T('提交')?>" /> </td>
			</tr>
		</tbody>
	</table>
</form>
</div>
