<?php 
$upload_form_uniqid = 'upload_form_'.uniqid();
$error_msg = I18N::T('nfs', '异常原因: 文件上传中止!');
?>
<div class="form padding_2" class="prevent_default">
	<form id="<?php echo $upload_form_uniqid?>" method="post" action="<?php echo URI::url('!nfs/nfs/upload.'.$object->name().'.'.$object->id.'.'.$path_type,['path'=>$path, 'form_token'=>$form_token])?>" class="nowrap" style="padding:1px">
		<input name="Filedata" type="file" class="middle" />
		<input name="single" type="hidden" value="1" />
		<a name="upload" href="#" class="button button_import middle prevent_default"><?php echo I18N::HT('nfs', '上传')?></a>
	</form>
</div>
<script>
jQuery(function($){
	var $form = $('#<?php echo $upload_form_uniqid?>');

	$form
	.find('a[name=upload]')
	.bind('click', function(){
		$form.ajaxSubmit({
			dataType: 'json',
			complete: function (data) {
				if (data.error == 'aborted' || data.aborted) {
					alert('<?php echo $error_msg?>');
				}
			},
			success : function(data, status, xhr) {

				Dialog.close();
				var $tbody = $('#<?php echo $form_id?>').find('tbody:eq(0)');
				$tbody.prepend(data);				
			}
		});
		return false;
	});

	$(document).bind('dialog_close', function(){

		$('iframe').remove();

		var $loadingBox = $('.loading_box');
		$loadingBox.trigger('ajaxComplete');

		return false;
	});
});
</script>
