<div style="width:440px" class="padding_1">
	<p class="padding_1"><?php echo T('尊敬的用户：'); ?></p>
	<p class="padding_1" style="text-indent:1.5em"><?php echo T('您好！'); ?></p>
	<p class="padding_1" style="text-indent:1.5em"><?php echo T('如果您所用的LabScout LIMS(以下简称LIMS)已经绑定该商城，请您先登录到LIMS，然后在订单列表中选择“进入商城”后跳转并进入商城。'); ?></p>
	<p class="padding_1" style="text-indent:1.5em"><?php echo T('如果您所用的LIMS尚未绑定该商城，请您联系实验室负责人，由其使用管理员账户进入商城，并绑定LIMS。'); ?></p>
	<p>&#160;</p>
</div>
