<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<title>
	<?php echo H($title ? T(Config::get('page.title_pattern'), array('%title'=>$title)) : Config::get('page.title_default'));
 ?>
</title>
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<base href="<?php echo Config::get('system.base_url') ?>" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="<?php echo _C('images/icon_touch.png') ?>" />
<?php echo $this->controller->load_css(); ?>
<?php echo $this->controller->load_js(TRUE); ?>
<script>
(function($){
	Q['24hour'] = <?php echo JS::quote(!!Config::get('system.24hour')); ?>;
})(jQuery);
</script>
</head>
<body>
<table  id="wrapper" cellpadding="0" cellspacing="0">
	<tr class="wrapper_header">
		<td>
			<div id="header">
				<div class="header_content"></div>
			</div>
		</td>
	</tr>
	
	<tr class="wrapper_body">
		<td valign="top">
			<div class="wrapper_body">
				<div id="body_header" class="clearfix"><?php echo $this->body_header; ?></div>
				<div id="body" class="clearfix">
					<div id="nav_tabs" class="clearfix"><?php echo $this->nav_tabs; ?></div>
					<div id="sub_body">
						<div id="sidebar" class="mall_sidebar"><?php echo $this->sidebar; ?></div>
						<div id="content"><?php echo V('message'); ?><?php echo $this->body; ?></div>
					</div>
				</div>
			</div>
		</td>
	</tr>
	
	<tr class="wrapper_footer">
		<td>
			<div id="footer">
				<div class="footer_content clearfix"><?php echo $this->footer; ?></div>
			</div>
		</td>
	</tr>
</table>
<?php echo $this->controller->load_js(FALSE); ?>
</body>
</html>
