<?php

$tags = array();
$t = $tag;
while ($t->id && $t->id != $root->id) {
	array_unshift($tags, $t);
	$t = $t->parent;
}
$real_root = $root->root->id ? $root->root : $root;

if ($root->id) {
	$children = Q("tag[root=$real_root][parent=$tag]");
	$has_children = $children->length() > 0;
	if (!$has_children) {
		array_pop($tags);
	}
} 

?>
<?php echo Form::hidden('root_id', $root->id); ?>
<?php echo Form::hidden($name, $tag->id); ?>
<div class="nowrap">
	<?php if ($tag->id == $root->id && !$has_children) {
		$root_class = 'tag_selector_last';
	}
	else {
		$root_class = 'tag_selector_first';
	}?>
	<div class="tag_selector_link <?php echo $root_class?>">
		   <?php echo (string) Widget::factory('tag_selector/link', array(
				   'name'=>$root_name ?: ($root->root->id ? $root->name : T('全部')),
				   'id'=>0
		   )); ?>
	</div><?php 
	foreach($tags as $t):
	?><div class="tag_selector_link">
	<?php echo (string) Widget::factory('tag_selector/link', array(
		   'name'=>$t->name,
		   'id'=>$t->id
	)); ?>
	</div><?php
 endforeach; ?>
<?php if ($has_children): 
	?><div class="tag_selector_link tag_selector_more tooltip:<?php echo HT('请点击');?> tooltip_position:left">&#160;</div><?php 
else: 
	if ($tag->id != $root->id) :
		?><div class="tag_selector_link tag_selector_last">
		<?php echo (string) Widget::factory('tag_selector/link', array(
			   'name'=>$tag->name,
			   'id'=>$tag->id
		)); ?>
		</div><?php 
	endif;?>
<?php endif; ?>
</div>
