<div class="padding_1 clearfix">
<table class="form">
<tbody>
<tr>
	<td class="top icon">
		<?php echo $product->icon('64'); ?>
	</td>
	<td class="top">
		<h2>
		<a href="<?php echo $product->url() ?>"><?php echo H($product->name); ?></a>
		<small>(<?php echo T($product->vendor->get_display_name('short')); ?>)</small>
		</h2>
	</td>
</tr>
</tbody>
</table>
<table class="form product_info_form">
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('单价')?></span></td>
		<td class="nowrap">
			<?php if (L('ME')->is_allowed_to('查看价格', $product)): ?>
				<?php echo V('application:common/price', array('price' => $product->unit_price, 'market_price' => $product->market_price)); ?>
			<?php else: ?>
				<span class="hidden_price">
					<?php echo HT('授权用户可见'); ?>
				</span>
			<?php endif; ?>
		</td>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('是否现货')?></span></td>
		<td>
			<?php
				$options = Product_Model::$stock_status;
				echo HT($options[$product->stock_status]);
			?>
		</td>
	</tr>
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('型号')?></span></td>
		<td class="nowrap"><?php echo H($product->model) ?></td>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('规格')?></span></td>
		<td><?php echo H($product->spec) ?></td>
	</tr>
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('包装')?></span></td>
		<td class="nowrap"><?php echo H($product->package) ?></td>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('关键字')?></span></td>
		<td><?php echo H(join(', ', json_decode($product->keywords, TRUE))) ?></td>
	</tr>
	<tr>
		<td class="nowrap tight top"><span class="status_tag status_tag_label"><?php echo T('说明')?></span></td>
		<td><?php echo $product->description; ?></td>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('供货时间')?></span></td>
		<td><?php echo HT('%supply_time 天', array('%supply_time'=>$product->supply_time)); ?></td>
	</tr>
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('产地')?></span></td>
		<td class=""><?php echo H($product->origin) ?></td>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('质保期')?></span></td>
		<td><?php echo H($product->warranty_period) ?></td>
	</tr>
	<tr>
		<td class="nowrap tight"><span class="status_tag status_tag_label"><?php echo T('服务电话')?></span></td>
		<td class="nowrap" colspan="3"><?php echo H($product->service_no) ?></td>
	</tr>
	<tr>
		<td class="nowrap tight top"><span class="status_tag status_tag_label"><?php echo T('商家备注')?></span></td>
		<td colspan="3"><?php echo $product->vendor_note; ?></td>
	</tr>
</table>
</div>