<div class="hr_1">&#160;</div>
<div class="form padding_1 clearfix">
	<form method="post"
	autocomplete="off"
	q-object="reject_statement"
	q-event="submit"
	q-src="<?php echo URI::url('!admin/financial/statement')?>"
	q-static="<?php echo H(array('id'=>$statement->id))?>">
    <?php echo V('form_error', array('form'=>$form))?>
		<table class="form flexible">
			<tr>
				<td class="label right nowrap top"><?php echo HT('理由')?></td>
				<td class="left">
				  <textarea name="reject_reason" class="text" rows="5" cols="40"></textarea>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" name="submit" class="button button_delete" value="<?php echo HT( $vendor->approve_date ? '下架' : '拒绝')?>" />
				</td>
			</tr>
		</table>
	</form>
</div>