<a href="<?php echo H($product->url(NULL, ['version'=>$product->version], NULL, 'admin_view')); ?>"><?php echo H($product->name); ?></a>
<?php
$sale_info = is_array($product->sale_info) ? $product->sale_info : json_decode($product->sale_info, true);
?>
<?php if ($info = $sale_info['info']) {?>
<br/>
<span class="status_tag" style="background-color:#F05568">
	<?php echo $info;?>
</span>
<?php
}
$extra_content = Event::trigger('order_item.product.table.extra_view', $item);
echo $extra_content;
?>
