<div class="hr_1">&#160;</div>
<div class="form padding_1">

<table class="user_grid form">
	<tbody>
	<tr>
		<td class="top icon">
			<?php echo $customer->icon('64');?>
		</td>
		<td class="top info">
            <form method="post" action="<?php echo URI::url() ?>" autocomplete="off">
                <table class="form flexible">
					<tr>
						<td class="label right nowrap top"><?php echo HT('信用等级')?></td>
                        <td class="left">
                            <?php foreach ($credits as $k=>$v) {?>
                            <label>
                                <input type="radio" name="credit" value="<?=H($k)?>"<?=$k==$customer->credit ? ' checked="checked"' : ''?> />
                                <?=$v?>
                            </label>
                            <?php }?>
                        </td>
					</tr>
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" name="submit" class="button button_save" value="<?php echo T('保存')?>" />
                        </td>
                    </tr>
                </table>
            </form>
        </td>
    </tr>
    </tbody>
</table>

